image: docker:cli

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apk --no-cache add curl

build-dev:
  script:
    - docker build -f docker/Containerfile --pull --tag "$CI_REGISTRY_IMAGE:dev" --build-arg=DEBUG_BUILD=true .
    - docker push "$CI_REGISTRY_IMAGE:dev"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

build-prod:
  script:
    - docker build -f docker/Containerfile --pull --tag "$CI_REGISTRY_IMAGE:prod" --build-arg=DEBUG_BUILD=false .
    - docker push "$CI_REGISTRY_IMAGE:prod"
    - docker tag "$CI_REGISTRY_IMAGE:prod" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - |
        curl -u "${PUSHBULLET_ACCESS_TOKEN}:" \
        -X POST https://api.pushbullet.com/v2/pushes \
        --header 'Content-Type: application/json' \
        --data-binary "{\"type\": \"note\", \"title\": \"hlo:prod pushed\", \"body\": \"hlo:prod pushed at @ $(date -Iminutes)\"}"
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
