image: docker:cli

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-dev:
  script:
    - docker build -f docker/Containerfile --pull --tag "$CI_REGISTRY_IMAGE:dev" --build-arg=DEBUG_BUILD=true .
    - docker push "$CI_REGISTRY_IMAGE:dev"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build-prod:
  script:
    - docker build -f docker/Containerfile --pull --tag "$CI_REGISTRY_IMAGE:prod" --build-arg=DEBUG_BUILD=false .
    - docker push "$CI_REGISTRY_IMAGE:prod"
    - docker tag "$CI_REGISTRY_IMAGE:prod" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
