image: docker:cli

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-dev:
  script:
    - docker build -f docker/Containerfile --pull --tag "homelab-organizer:dev" --build-arg=DEBUG_BUILD=true .
    - docker push "homelab-organizer:dev"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build-prod:
  script:
    - docker build -f docker/Containerfile --pull --tag "homelab-organizer:prod" --build-arg=DEBUG_BUILD=false .
    - docker push "homelab-organizer:prod"
    - docker tag "homelab-organizer:prod" "homelab-organizer:latest"
    - docker push "homelab-organizer:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "stable"
