# Generated by Django 4.2.13 on 2024-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_secondary",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="name_secondary",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="storage",
            name="name_secondary",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
