# Generated by Django 4.2.13 on 2024-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0002_category_name_secondary_project_name_secondary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="thumnail_sha1",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=40
            ),
        ),
    ]
