# Generated by Django 4.2.13 on 2024-05-12 11:04

from django.db import migrations, models

import hlo.models.stockitem
import hlo.utils.overwritingfilestorage


class Migration(migrations.Migration):
    dependencies = [
        ("hlo", "0003_stockitem_thumnail_sha1"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                storage=hlo.utils.overwritingfilestorage.OverwritingFileSystemStorage(),
                upload_to=hlo.models.stockitem.thumbnail_path,
            ),
        ),
    ]
