# Generated by Django 4.2.13 on 2024-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0004_stockitem_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockitem",
            old_name="thumnail_sha1",
            new_name="thumbnail_sha1",
        ),
        migrations.AddField(
            model_name="stockitem",
            name="count_unit",
            field=models.CharField(default="items", max_length=50, verbose_name="Unit"),
        ),
    ]
