# Generated by Django 4.2.13 on 2024-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0006_rename_thumnail_sha1_orderitem_thumbnail_sha1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="attachements",
            field=models.ManyToManyField(
                blank=True, related_name="order", to="hlo.attachement"
            ),
        ),
    ]
