# Generated by Django 4.2.13 on 2024-05-29 15:24

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0008_alter_orderitem_attachements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="tax_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "$"), ("NOK", "kr"), ("JPY", "¥"), ("EUR", "€")],
                default=None,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
