# Generated by Django 4.2.13 on 2024-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0009_alter_order_shipping_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
