# Generated by Django 4.2.13 on 2024-07-13 13:32

from django.db import migrations, models

import hlo.models.stockitem


def create_sha1s(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    StockItem = apps.get_model("hlo", "StockItem")
    for item in StockItem.objects.all():
        item.sha1 = hlo.models.stockitem.make_uuid_sha1()
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("hlo", "0010_stockitem_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="sha1",
            field=models.CharField(
                default="",
                editable=False,
                max_length=40,
            ),
        ),
        migrations.RunPython(create_sha1s),
        migrations.AlterField(
            model_name="stockitem",
            name="sha1",
            field=models.CharField(
                default=hlo.models.stockitem.make_uuid_sha1,  # probably not needed?
                editable=False,
                max_length=40,
            ),
        ),
    ]
