# Generated by Django 4.2.13 on 2024-07-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0011_stockitem_sha1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockitem",
            old_name="sha1",
            new_name="sha1_id",
        ),
    ]
