# Generated by Django 4.2.14 on 2024-08-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0012_rename_sha1_stockitem_sha1_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="attachements",
            new_name="attachments",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="attachements",
            new_name="attachments",
        ),
        migrations.RenameField(
            model_name="stockitem",
            old_name="attachements",
            new_name="attachments",
        ),
    ]
