# Generated by Django 4.2.14 on 2024-08-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0013_rename_attachements_order_attachments_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attachement",
            new_name="Attachment",
        ),
    ]
