# Generated by Django 4.2.14 on 2024-08-02 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hlo", "0014_rename_attachement_attachment"),
    ]
    #
    operations = [
        migrations.RunSQL(
            (
                "UPDATE hlo_attachment "
                "SET file = replace(file, 'attachements/', 'attachments/') "
                "WHERE file LIKE 'attachements/%'"
            ),
        ),
    ]
