# Generated by Django 4.2.14 on 2024-11-15 23:18

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("hlo", "0016_alter_stockitem_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="label_printed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_id",
            field=models.CharField(
                default="",
                help_text="The original item id from the shop. Not to be confused with the internal database id.",
                max_length=100,
                verbose_name="Shop item ID",
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
