# Generated by Django 5.1.3 on 2024-11-18 19:54

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hlo", "0018_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_nok",
            field=models.GeneratedField(
                db_persist=False,
                expression=models.Case(
                    models.When(
                        then=django.db.models.expressions.CombinedExpression(
                            models.F("total"), "*", models.Value(0.0716)
                        ),
                        total_currency="JPY",
                    ),
                    models.When(
                        then=django.db.models.expressions.CombinedExpression(
                            models.F("total"), "*", models.Value(11.1)
                        ),
                        total_currency="USD",
                    ),
                    models.When(
                        then=django.db.models.expressions.CombinedExpression(
                            models.F("total"), "*", models.Value(14.02)
                        ),
                        total_currency="GBP",
                    ),
                    models.When(
                        then=django.db.models.expressions.CombinedExpression(
                            models.F("total"), "*", models.Value(11.72)
                        ),
                        total_currency="EUR",
                    ),
                    default=models.F("total"),
                    output_field=models.DecimalField(decimal_places=4, max_digits=19),
                ),
                output_field=models.DecimalField(decimal_places=4, max_digits=19),
            ),
        ),
    ]
